project:
  type: website

website:
  title: "Junnan"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd

format:
  html:
    theme: cosmo
    css: styles.scss
    toc: false



